source "http://rubygems.org"

gem "rails", "<%= rails_gem_version %>"
gem "sqlite3-ruby", :require => "sqlite3"
gem "i18n", "<%= i18n_version %>"

gem "rich_pluralization", :path => File.expand_path("../../../..", __FILE__)

group :test do
  gem "mysql"
  gem "shoulda"
  gem "mocha"
  gem "capybara"
  gem "launchy"
end