source "http://rubygems.org"

gem "rails", "3.0.6"
gem "sqlite3-ruby", :require => "sqlite3"
gem "i18n", "0.5.0"

gem "rich_pluralization", :path => File.expand_path("../../../..", __FILE__)

group :test do
  gem "mysql"
  gem "shoulda"
  gem "mocha"
  gem "capybara"
  gem "launchy"
end